### PR TITLE
Be explicit with remote and revision

### PR DESCRIPTION
**Pull request by PeterHindes**

### CODE REVIEW

**Comment by zifnab06** [comment]
Not everyone has a 'github' remote defined.

**Comment by PeterHindes** [comment]
ok, well, its kinda non functional for some rom repos, ie aospexteded, so it should have some way of working universally, what do you recommend?

**Comment by mikeNG** [comment]
Fix your ROM?

**Comment by PeterHindes** [comment]
it's not my rom. Im just concerned that this manifest provided here may not
be as resilient/portable as it should be.

**Pull request closed without merging**
