### PR TITLE
create locale_manifest.xml

### PR DESCRIPTION
**Pull request by AndroidDes**
I modifide the muppets manifest so you can run [ git clone https://github.com/TheMuppets/local_manifest.git   /{your local source tree}/.repo/manifests/locale_manifest/locale_manifest.xml ] then run repo sync to add all muppets vendor files to  local source.

### CODE REVIEW

**Comment by invisiblek** [comment]
the name of the xml doesn't matter. just use the muppets.xml that's already provided.

**Comment by AndroidDes** [comment]
it has nothing to do with the name view the contents

**Comment by Tortel** [comment]
The main muppets.xml will work fine as a local manifest. All the extra crap is not needed

**Comment by invisiblek** [comment]
*IF* you're using a manifest that has the right default remote set up. other roms may not work

**Pull request closed without merging**
