### PR TITLE
Add common ti vendor

### PR DESCRIPTION
**Pull request by andi34**

### CODE REVIEW

**Comment by andi34** [comment]
Tab 2 switched, tuna switched, motorola omap4 switched. should be good to go.

**Comment by invisiblek** [comment]
create a proper branch, we shouldn't use 'master'

**Comment by andi34** [comment]
nooooo, one stable branch. this works from 4.4 up to 7.1 without messing with different branches

**Comment by andi34** [comment]
Doesn't matter

**Pull request merged**
